### ISSUE TITLE
ElasticityTensorR4 stuff

### ISSUE THREAD

**Issue by dschwen** [idaholab/hyrax#1]
Hello @amjokisaari, I was unaware of this repo and made a PR on the old UMThornton repo two weeks ago. That patch doesn't apply here (apparently you've been a busy bee!). 

Check out the diff here:
https://github.com/UMThorntonGroup/Hyrax/pull/15/files

to see how to fix that stuff

**Comment by dschwen** [comment]
Looks like for Hyrax all that was needed was replacing `ElasticityTensorR4` with `RankFourTensor`

**Comment by amjokisaari** [comment]
Thanks, @dschwen. I've discussed with @permcody about the forking of Hyrax from UMThorntonGroup to Idaholab, and I appreciate you taking a look at this version too. I've graduated from Dr. Thornton's group, but I'm continuing to develop Hyrax.  Thus, I'd like to keep all my development on the Idaholab fork in case any future graduate students would like to develop the UMThorntonGroup fork.  

Also, thanks for the note - I have make sure my new application that I'm developing with Olle (Hedgehog) is up to date with the RankFourTensor update.

**Comment by dschwen** [comment]
By the way, will you be at Northwestern for the Hackathon in a week?

**Comment by amjokisaari** [comment]
I will be!  I will not be participating, but I'll be there to help out.
Are you attending?

**Comment by dschwen** [comment]
Yeah, we'll have a team there. I guess you are involved with setting up the problems then...

**Comment by amjokisaari** [comment]
Yes, we sent them to Jim Warren and Peter Voorhees today and they are ok
with them.  There will be an email going out next week to give you a heads
up as to the types of problems you'll be working on.
